version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: tg-go-bot
    restart: always
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
    - "5432:5432"
